# This workflow will run when a PR is merged into main

name: Packages publisher

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish-gpr:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'publish-packages')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
